# Site settings
title: 高性能网站
sub_title: BestPerf.com 追求最佳性能
email: admin@bestperf.com
description: "Everything Web/Mobile Performance"
baseurl: ""
url: "http://bestperf.com"
usernames:
  github: Lax
  twitter: liulantao

# Build settings
markdown: kramdown
permalink: pretty
